class Watcher:
    def start(self):
        ...

    def stop(self):
        ...
class Action:
    def execute(self):
        ...
class ProcessWatcher(Watcher):
    ...
class BatteryWatcher(Watcher):
    ...